(part "GPTS203212B"
    (packageRef "GPTS203212B")
    (interface
        (port "1" (symbPinId 1) (portName "ON") (portType INOUT))
        (port "6" (symbPinId 2) (portName "OFF") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "629-GPTS203212B")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=629-GPTS203212B")
    (property "Manufacturer_Name" "CW Industries")
    (property "Manufacturer_Part_Number" "GPTS203212B")
    (property "Description" "Pushbutton Switches SPST ON-OFF")
    (property "Datasheet_Link" "http://switches-connectors-custom.cwind.com/Asset/GPTS203212BR2.pdf")
    (property "symbolName1" "GPTS203212B")
)
